version: '3'
services:
  api:
    build: 
      context: ./api
    volumes:
      - ./api:/code    
    ports:
      - "5000:5000"
    restart: always
  webapp:
    build: 
      context: ./app
    volumes:
      - ./app:/www    
    ports:
      - "3000:3000"
    restart: always           